# Generated by Django 5.2.5 on 2025-09-15 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_coupon'),
        ('payments', '0003_alter_payment_order_alter_payment_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='order',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='orders.order'),
            preserve_default=False,
        ),
    ]
