# Generated by Django 5.2.5 on 2025-09-04 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_cancel_approved_order_cancel_approved_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('partially_cancelled', 'Partially Cancelled'), ('return_requested', 'Return Requested'), ('returned', 'Returned'), ('partially_returned', 'Partially Returned')], default='pending', max_length=30),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('cancel_requested', 'Cancel Requested'), ('cancelled', 'Cancelled'), ('delivered', 'Delivered'), ('return_requested', 'Return Requested'), ('returned', 'Returned'), ('return_rejected', 'Return Rejected')], default='active', max_length=20),
        ),
    ]
