# Generated by Django 5.2.5 on 2025-09-07 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0002_couponusage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='discount',
            field=models.DecimalField(decimal_places=2, help_text='Enter discount in % (e.g., 10 = 10%)', max_digits=10),
        ),
    ]
