# Generated by Django 5.2.5 on 2025-09-13 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0003_alter_coupon_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='max_discount_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Maximum discount amount allowed (e.g., 500 for ₹500 cap)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='coupon',
            name='min_order_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Minimum order subtotal required to apply coupon', max_digits=10, null=True),
        ),
    ]
