# Generated by Django 5.2.5 on 2025-09-15 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0004_coupon_max_discount_amount_coupon_min_order_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='discount',
            field=models.DecimalField(decimal_places=2, help_text='Enter discount in % (e.g., 10 = 10%)', max_digits=5),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='max_discount_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Maximum discount amount allowed (e.g., 500 for ₹500 cap)', max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='min_order_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Minimum order subtotal required to apply coupon', max_digits=8, null=True),
        ),
    ]
