# Generated by Django 5.2.5 on 2025-09-15 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0005_alter_coupon_discount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='is_referral',
            field=models.BooleanField(default=False, help_text='Mark True if this is a referral-only coupon'),
        ),
    ]
