# Generated by Django 5.2.5 on 2025-08-21 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_varianttype_remove_product_main_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='varianttype',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
