# Generated by Django 5.2.5 on 2025-08-21 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_category_is_active_varianttype_is_active'),
    ]

    operations = [
    ]
