# Generated by Django 5.2.5 on 2025-08-21 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20250821_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='variant_type',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='VariantType',
        ),
    ]
