# Generated by Django 5.2.5 on 2025-08-21 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_productvariant_variant_type_delete_varianttype'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='watering',
            field=models.TextField(blank=True, null=True),
        ),
    ]
