# Generated by Django 5.2.5 on 2025-09-19 11:28

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_productvariant_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variantimage',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
