# Generated by Django 5.2.5 on 2025-09-22 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_order_status_alter_orderitem_status'),
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='admintransaction',
            name='source_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.order'),
        ),
    ]
