# Generated by Django 5.2.5 on 2025-09-20 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_adminwallet_transaction'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdminWallet',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
